name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: MacVimSwitch-x86_64
            asset_name: MacVimSwitch-x86_64
            arch: x86_64
          - os: macos-latest
            artifact_name: MacVimSwitch-arm64
            asset_name: MacVimSwitch-arm64
            arch: arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build Binary
      run: |
        mkdir -p build
        target=""
        if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
          export target="x86_64"
        else
          export target="arm64"
        fi
        swiftc -o build/macvimswitch macvimswitch.swift -framework Cocoa -framework Carbon -target ${target}-apple-macos11

    - name: Create Package
      run: |
        # 创建标准的 macOS 应用包结构
        mkdir -p dist/MacVimSwitch.app/Contents/{MacOS,Resources}
        
        # 复制可执行文件
        cp build/macvimswitch dist/MacVimSwitch.app/Contents/MacOS/
        
        # 创建 Info.plist
        cat > dist/MacVimSwitch.app/Contents/Info.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>macvimswitch</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.jackiexiao.macvimswitch</string>
            <key>CFBundleName</key>
            <string>MacVimSwitch</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${{ steps.get_version.outputs.VERSION }}</string>
            <key>LSMinimumSystemVersion</key>
            <string>11.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.utilities</string>
        </dict>
        </plist>
        EOL
        
        # 添加应用图标（如果有的话）
        # cp AppIcon.icns dist/MacVimSwitch.app/Contents/Resources/
        
        # 创建压缩包
        cd dist
        zip -r ../MacVimSwitch-${{ matrix.arch }}.zip MacVimSwitch.app
        cd ..

    - name: Calculate SHA256
      run: |
        shasum -a 256 MacVimSwitch-${{ matrix.arch }}.zip | cut -d ' ' -f 1 > sha256-${{ matrix.arch }}.txt
      id: sha256

    - name: Upload SHA256
      uses: actions/upload-artifact@v4
      with:
        name: sha256-${{ matrix.arch }}
        path: sha256-${{ matrix.arch }}.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: MacVimSwitch-${{ matrix.arch }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: MacVimSwitch ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            MacVimSwitch-x86_64/MacVimSwitch-x86_64.zip
            MacVimSwitch-arm64/MacVimSwitch-arm64.zip
          body: |
            MacVimSwitch ${{ steps.get_version.outputs.VERSION }}
            
            - ARM64 (Apple Silicon)
            - x86_64 (Intel)

      - name: Download SHA256s
        uses: actions/download-artifact@v4
        with:
          pattern: sha256-*
          merge-multiple: true

      - name: Update Formula
        run: |
          ARM64_SHA256=$(cat sha256-arm64.txt)
          X86_64_SHA256=$(cat sha256-x86_64.txt)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Create updated formula
          sed -i "s/PLACEHOLDER_VERSION/$VERSION/" macvimswitch.rb
          sed -i "s/PLACEHOLDER_ARM64_SHA256/$ARM64_SHA256/" macvimswitch.rb
          sed -i "s/PLACEHOLDER_X86_64_SHA256/$X86_64_SHA256/" macvimswitch.rb

      - name: Upload Updated Formula
        uses: actions/upload-artifact@v4
        with:
          name: updated-formula
          path: macvimswitch.rb

  update-homebrew:
    name: Update Homebrew Tap
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download updated formula
        uses: actions/download-artifact@v4
        with:
          name: updated-formula
          path: ./

      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: 'jackiexiao/homebrew-tap'
          token: ${{ secrets.TAP_TOKEN }}
          path: homebrew-tap

      - name: Update Formula
        run: |
          cd homebrew-tap
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          branch_name="update-macvimswitch-${{ steps.get_version.outputs.VERSION }}"
          git checkout -b $branch_name
          
          cp ../macvimswitch.rb Formula/
          
          git add Formula/macvimswitch.rb
          git commit -m "feat: update macvimswitch to ${{ steps.get_version.outputs.VERSION }}"
          git push origin $branch_name

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TAP_TOKEN }}
          path: homebrew-tap
          title: "feat: update macvimswitch to ${{ steps.get_version.outputs.VERSION }}"
          body: |
            Updates MacVimSwitch to version ${{ steps.get_version.outputs.VERSION }}
            
            - Updates version to ${{ steps.get_version.outputs.VERSION }}
            - Updates SHA256 hashes for both ARM64 and x86_64 builds
            
            This PR was automatically generated by GitHub Actions.
          base: main
          delete-branch: true