name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Create App Bundle
      run: |
        # 创建目录结构
        mkdir -p dist/MacVimSwitch.app/Contents/{MacOS,Resources}
        
        # 编译
        swiftc -o dist/MacVimSwitch.app/Contents/MacOS/macvimswitch macvimswitch.swift \
          -framework Cocoa \
          -framework Carbon \
          -target arm64-apple-macos11 \
          -O \
          -whole-module-optimization \
          -Xlinker -rpath \
          -Xlinker @executable_path/../Frameworks
        
        # 创建 Info.plist
        cat > dist/MacVimSwitch.app/Contents/Info.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>macvimswitch</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.jackiexiao.macvimswitch</string>
            <key>CFBundleName</key>
            <string>MacVimSwitch</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${GITHUB_REF#refs/tags/v}</string>
            <key>LSMinimumSystemVersion</key>
            <string>11.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.utilities</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSAppleEventsUsageDescription</key>
            <string>MacVimSwitch needs to control system events to manage input sources.</string>
            <key>NSAppleScriptEnabled</key>
            <true/>
            <key>LSBackgroundOnly</key>
            <false/>
        </dict>
        </plist>
        EOL
        
        # 创建 entitlements.plist
        cat > entitlements.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>com.apple.security.automation.apple-events</key>
            <true/>
            <key>com.apple.security.temporary-exception.apple-events</key>
            <array>
                <string>com.apple.systemevents</string>
            </array>
            <key>com.apple.security.cs.allow-jit</key>
            <true/>
            <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
            <true/>
            <key>com.apple.security.cs.disable-library-validation</key>
            <true/>
        </dict>
        </plist>
        EOL
        
        # 设置执行权限
        chmod +x dist/MacVimSwitch.app/Contents/MacOS/macvimswitch
        
        # 使用自签名
        codesign --force --deep --sign - --entitlements entitlements.plist dist/MacVimSwitch.app

    - name: Create DMG
      run: |
        # 创建 DMG
        hdiutil create -volname "MacVimSwitch" -srcfolder dist/MacVimSwitch.app -ov -format UDZO MacVimSwitch.dmg

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MacVimSwitch.dmg
        asset_name: MacVimSwitch.dmg
        asset_content_type: application/x-apple-diskimage

    - name: Calculate SHA256
      run: |
        echo "DMG_SHA256=$(shasum -a 256 MacVimSwitch.dmg | cut -d ' ' -f 1)" >> $GITHUB_ENV

    - name: Add SHA256 to Release
      uses: softprops/action-gh-release@v1
      with:
        files: MacVimSwitch.dmg
        body: |
          SHA256: ${{ env.DMG_SHA256 }}
          
          You can verify the SHA256 checksum of the DMG file using:
          ```bash
          shasum -a 256 MacVimSwitch.dmg
          ```
          
          Note: This is an unsigned application. When first opening it:
          1. Right-click the app and select "Open"
          2. Click "Open" in the security dialog
          3. Grant necessary permissions in System Preferences > Security & Privacy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}