name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Binaries
      run: |
        # 获取版本号
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Building version ${VERSION}"
        
        # 创建构建目录
        mkdir -p build/{arm64,x86_64}
        
        # 编译 ARM64 版本
        swiftc -o build/arm64/macvimswitch macvimswitch.swift -framework Cocoa -framework Carbon -target arm64-apple-macos11
        
        # 编译 x86_64 版本
        swiftc -o build/x86_64/macvimswitch macvimswitch.swift -framework Cocoa -framework Carbon -target x86_64-apple-macos11
        
        # 创建通用二进制
        lipo -create build/arm64/macvimswitch build/x86_64/macvimswitch -output build/macvimswitch
        
    - name: Create Packages
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # 创建目录结构
        mkdir -p dist/{arm64,x86_64,universal}/MacVimSwitch.app/Contents/{MacOS,Resources}
        mkdir -p dist/{arm64,x86_64,universal}/Library/LaunchAgents
        
        # 复制启动配置
        for ARCH in arm64 x86_64 universal; do
          cat > dist/$ARCH/Library/LaunchAgents/com.jackiexiao.macvimswitch.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>com.jackiexiao.macvimswitch</string>
            <key>Program</key>
            <string>/usr/local/bin/macvimswitch</string>
            <key>RunAtLoad</key>
            <true/>
            <key>KeepAlive</key>
            <true/>
        </dict>
        </plist>
        EOL
        
          cat > dist/$ARCH/MacVimSwitch.app/Contents/Info.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>macvimswitch</string>
            <key>CFBundleIdentifier</key>
            <string>com.jackiexiao.macvimswitch</string>
            <key>CFBundleName</key>
            <string>MacVimSwitch</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${VERSION}</string>
            <key>LSMinimumSystemVersion</key>
            <string>11.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOL
        done
        
        # 复制可执行文件
        cp build/arm64/macvimswitch dist/arm64/MacVimSwitch.app/Contents/MacOS/
        cp build/x86_64/macvimswitch dist/x86_64/MacVimSwitch.app/Contents/MacOS/
        cp build/macvimswitch dist/universal/MacVimSwitch.app/Contents/MacOS/
        
        # 创建压缩包
        cd dist
        zip -r ../MacVimSwitch-arm64.zip arm64/MacVimSwitch.app arm64/Library
        zip -r ../MacVimSwitch-x86_64.zip x86_64/MacVimSwitch.app x86_64/Library
        zip -r ../MacVimSwitch-universal.zip universal/MacVimSwitch.app universal/Library
        cd ..
        
        # 创建源代码包（用于 Homebrew）
        mkdir -p "macvimswitch-${VERSION}"
        cp macvimswitch.swift README.md README_CN.md LICENSE "macvimswitch-${VERSION}/"
        cp -r dist/universal/Library "macvimswitch-${VERSION}/"
        tar czf "macvimswitch-${VERSION}.tar.gz" "macvimswitch-${VERSION}"

    - name: Calculate SHA256
      id: sha
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        HASH=$(shasum -a 256 "macvimswitch-${VERSION}.tar.gz" | awk '{print $1}')
        echo "tarball_hash=${HASH}" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: MacVimSwitch ${{ github.ref_name }}
        body: |
          MacVimSwitch ${{ github.ref_name }}
          
          - Universal Binary (Intel + Apple Silicon)
          - ARM64 (Apple Silicon)
          - x86_64 (Intel)
          
          SHA256 for Homebrew: `${{ steps.sha.outputs.tarball_hash }}`
          
          Please update the SHA256 in the Homebrew formula:          ```ruby
          class Macvimswitch < Formula
            url "https://github.com/jackiexiao/macvimswitch/archive/${{ github.ref_name }}.tar.gz"
            sha256 "${{ steps.sha.outputs.tarball_hash }}"
          end          ```
        draft: false
        prerelease: false
        
    - name: Upload Universal App Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MacVimSwitch-universal.zip
        asset_name: MacVimSwitch-universal.zip
        asset_content_type: application/zip
        
    - name: Upload ARM64 App Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MacVimSwitch-arm64.zip
        asset_name: MacVimSwitch-arm64.zip
        asset_content_type: application/zip
        
    - name: Upload x86_64 App Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MacVimSwitch-x86_64.zip
        asset_name: MacVimSwitch-x86_64.zip
        asset_content_type: application/zip
        
    - name: Upload Source Tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./macvimswitch-${{ github.ref_name }}.tar.gz
        asset_name: macvimswitch-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip